//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2012CSharp.CLI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHocBong
    {
        public long IdLHB { get; set; }
        public string Ten { get; set; }
        public Nullable<double> DiemHB_CanDuoi { get; set; }
        public Nullable<double> DiemHB_CanTren { get; set; }
        public Nullable<decimal> MucTien { get; set; }
    }
}
