//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2012CSharp.CLI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetSinhVien
    {
        public string TenKhoa { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public string TenMonHoc { get; set; }
        public double Diem { get; set; }
    }
}
