//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2012.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTitle
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int PublisherId { get; set; }
        public int AuthorId { get; set; }
        public int ReleaserId { get; set; }
        public int BookTypeId { get; set; }
        public string Image { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public Nullable<int> PageNo { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
