//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2012.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Publisher
    {
        public int Id { get; set; }
        [Required]
        [StringLength(15, MinimumLength = 8, ErrorMessage = "Mã không được nhỏ hơn 8 ký tự và lớn hơn 15 ký tự")]
        [DisplayName("Mã NXB")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Tên không được để trống")]
        [DisplayName("Tên NXB")]
        public string Name { get; set; }

        [DisplayName("Chú thích")]
        public string Notes { get; set; }

        [Required]
        [Range(0, 1, ErrorMessage = "Trạng thái chỉ có thể là 0 hoặc 1")]
        [DisplayName("Trạng thái")]
        public Nullable<byte> Status { get; set; }

        public Nullable<bool> IsDelete { get; set; }
    }
}
